# Generated by Django 5.1.3 on 2024-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
